version: "3"
services:
  weasyprint-rest:
    build: 
      context: .
      dockerfile: dev.Dockerfile
    ports: 
      - 5000:5000
    environment: 
      API_KEY:
      ALLOWED_URL_PATTERN: ^https?://(.*\.)google.com/.*$$
    volumes:
      - ./tests/resources/templates:/data/templates

