name: Publish

on:
  workflow_run:
    workflows: ["Build, Test, Lint"]
    types: 
      - completed
    branches:
      - main
    tags:
      - '*'
  # push:

jobs:
  push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set env
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF#*/*/})
    - name: Docker Login (docker.pkg.github.com)
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Login (docker.io)
      uses: azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push docker images
      run: make push-all VERSION=${{ env.RELEASE_VERSION }}
