name: Publish

on:
  workflow_run:
    workflows: ["Build, Test, Lint"]
    types: 
      - completed
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
#   - '*'
# push:
#   branches:
#   - main
#   tags:
#   - '*'

jobs:
  needs: build
  push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set env
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Docker Login (docker.pkg.github.com)
      uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # - name: Docker Login (docker.io)
    #   uses: azure/docker-login@v1
    #   with:
    #     username: ${{ secrets.DOCKERIO_USERNAME }}
    #     password: ${{ secrets.DOCKERIO_PASSWORD }}
    # - name: Log into Registry
    #   run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Push to GitHub Package Registry
      run: make push VERSION=${{ env.RELEASE_VERSION }}
